name: linux 

on:
  pull_request:
    branches: [ master ]

  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  h5bench:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - uses: actions/checkout@v2

      - name: Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install libtool
          sudo apt-get install zlib1g-dev
          sudo apt-get install python3
          sudo apt-get install libopenmpi-dev
          sudo apt-get install libhdf5-mpi-dev
        
      - name: Compile/Build H5bench SYNC
        run: |
          mkdir build_sync
          cd build_sync
          cmake .. -DCMAKE_C_COMPILER=/usr/bin/h5pcc
          make
